// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using S3FileLoadApi.Framework;

namespace S3FileLoadApi.Framework.Migrations
{
    [DbContext(typeof(RequestStatDbContext))]
    [Migration("20200730081258_InitRequestStatDbMigration")]
    partial class InitRequestStatDbMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("S3FileLoadApi.Models.ObjectGetRequestStat", b =>
                {
                    b.Property<Guid>("RequestUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentMd5Hash")
                        .HasColumnType("text");

                    b.Property<long>("ElapsedMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrMsg")
                        .HasColumnType("text");

                    b.Property<bool>("Md5HashMatch")
                        .HasColumnType("boolean");

                    b.Property<string>("ObjectName")
                        .HasColumnType("text");

                    b.Property<string>("ProcessingHost")
                        .HasColumnType("text");

                    b.Property<string>("RemoteClientHost")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestCompleateDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("RequestStartDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("integer");

                    b.HasKey("RequestUuid");

                    b.ToTable("RequestStat");
                });
#pragma warning restore 612, 618
        }
    }
}
